services:
  postgres:
    image: postgres:16-alpine
    container_name: relay_postgres
    environment:
      POSTGRES_USER: relay
      POSTGRES_PASSWORD: relay_secret
      POSTGRES_DB: relay_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U relay -d relay_db"]
      interval: 5s
      timeout: 5s
      retries: 5



  redis:
    image: redis:7-alpine
    container_name: relay_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5



  asynqmon:
    image: hibiken/asynqmon
    container_name: relay_asynqmon
    ports:
      - "8080:8080"
    environment:
      - REDIS_ADDR=redis:6379
    depends_on:
      - redis



volumes:
  postgres_data:
  redis_data: